# Generated by Django 4.0.3 on 2022-05-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(max_length=2500),
        ),
    ]
