# Generated by Django 4.0.3 on 2022-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_destination_slug_alter_destination_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(max_length=2500)),
                ('destination', models.ManyToManyField(related_name='destination', to='bus.destination')),
            ],
        ),
    ]
